spring.application.name=multivendor
spring.datasource.url=jdbc:mysql://localhost:3306/multivendor
spring.datasource.username=root
spring.datasource.password=Kartik@1284

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true
